#─────────────────────────── Basic variables ────────────────────────────
CXX        := g++
CXXFLAGS   := -std=c++17 -Wall -Wextra -O2 -MMD -MP
INC_DIRS   := -Isrc     #includes headers in src/

OBJ_DIR    := makemagic/obj #build dirs
BIN_DIR    := makemagic/bin

#─────────────────────────── Common sources ─────────────────────────────
COMMON_SRC := src/data.cpp src/tree_utils.cpp

#────────── BST ──────────
BST_SRC    := $(COMMON_SRC) \
			  src/bst/bst.cpp \
			  src/bst/main_bst.cpp
BST_OBJ    := $(patsubst src/%.cpp,$(OBJ_DIR)/%.o,$(BST_SRC))
BST_BIN    := $(BIN_DIR)/bst

#────────── AVL ──────────
#TODO

#───────────────────────── Compilation/link ─────────────────────────────
$(OBJ_DIR)/%.o: src/%.cpp #generic rule to create *.o in the object directory
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $(INC_DIRS) -c $< -o $@


$(BST_BIN): $(BST_OBJ) #links the BST binary
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $^ -o $@

#───────────────────────── Utility targets ──────────────────────────────
run-bst: $(BST_BIN)
	$< search 10 data  

.PHONY: clean #cleaning
clean:
	rm -rf makemagic

-include $(wildcard $(OBJ_DIR)/**/*.d) #includes dependencies generated by -MMD

